package ir.newims.ims.business.personnel.request;

public interface RequestCode {
    String REQUEST_LOG_TYPE = "REQUEST_LOG_TYPE";
    String LEAVE_REQUEST_LOG_TYPE = "LEAVE_REQUEST_LOG_TYPE";
    String FOOT_WORK_LOG_TYPE = "FOOT_WORK_LOG_TYPE";


    String REQUEST_STATUS = "REQUEST_STATUS";

    String REJECTED_REQUEST_STATUS = "REJECTED_REQUEST_STATUS";
    String CONFIRMED_REQUEST_STATUS = "CONFIRMED_REQUEST_STATUS";
    String REGISTERED_REQUEST_STATUS = "REGISTERED_REQUEST_STATUS";


}
