version: "3"

services:
  mysql:
    image: mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: '12345dbtest'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'dani-db'
      MYSQL_USER: 'daniel'
      MYSQL_PASSWORD: '12345test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
        - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: