package ir.newims.ims.business.personnel.leaverequest;

public interface LeaveRequestCode {
    String REQUEST_TYPE = "REQUEST_TYPE";
    String REQUEST_STATUS = "REQUEST_STATUS";

    String ENTITLEMENT_REQUEST_TYPE = "ENTITLEMENT_REQUEST_TYPE";
    String FOR_INFORMATION_REQUEST_TYPE = "FOR_INFORMATION_REQUEST_TYPE";
    String ILLNESS_REQUEST_TYPE = "ILLNESS_REQUEST_TYPE";

    String REJECTED_REQUEST_STATUS = "REJECTED_REQUEST_STATUS";
    String CONFIRMED_REQUEST_STATUS = "CONFIRMED_REQUEST_STATUS";
    String REGISTERED_REQUEST_STATUS = "REGISTERED_REQUEST_STATUS";

}
